# Generated by Django 4.1.7 on 2023-03-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        auto_created=True, blank=True, primary_key=True, serialize=False
                    ),
                ),
                ("age", models.IntegerField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=1)),
                (
                    "height",
                    models.DecimalField(
                        blank=True, decimal_places=5, max_digits=10, null=True
                    ),
                ),
            ],
        ),
    ]
