services:
  
  db:
    image: docker.io/postgres:15.2-alpine
    restart: on-failure
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=contra

  backend:
    build: 
      dockerfile: Containerfile
      context: Backend
    restart: on-failure
    expose:
      - 8000
    ports:
      - "8000:8000"
      
  frontend:
    build:
      dockerfile: Containerfile
      context: frontend
    restart: on-failure
    ports:
      - "3000:3000"